import { useState } from 'react';
import { Button, StyleSheet, Text, TextInput, View,ScrollView,FlatList } from 'react-native';

export default function App() {
  const [goal,setGoal]=useState('')
  const [goalList,setGoalList]=useState([])

  //by default flexbox is enabled
  //the main axis depends on the flex direction ,the other axis is the cross axis
  //the elements got stretched along 
  //justify-content=>is to organize elements along main axis
  //align-items=>is to organize elements along cross axis
  //css used here doesnot support inheritance like it used to in web

  //sometimes you have to write short snippets of code or 
  //add an extra wrapper (like View) to enable a particular style 
  //or effect on deifferent platforms(like ios)
  
  return (
    <View style={styles.appContainer}>
      <View style={styles.inputContainer}> 
        <TextInput style={styles.textInput} placeholder='Your course goal!' onChangeText={(e)=>setGoal(e)}/>
        <Button title='Add Goal' onPress={()=>{
          setGoalList(goals=>[...goals,{text:goal,id:Math.random().toString()}])}}/>
      </View>
      <View style={styles.goalContainer}>
        {/* ScrollView is preferable in articles,etc. but not in lists.
        ScroolView=ListView
        The prefered is FlatList
        FlatList=RecyclerView */}
        <FlatList 
          data={goalList} 
          renderItem={(itemdata)=>{
            //itemdata is the individual goal from the goalList 
            //with some meta-data generated by FlatList
            return ( 
              <View style={styles.goalItem}>
                <Text style={{color:'white'}}>{itemdata.item.text}</Text>
                {/* flatlist will automatically read the 'key' attribute from the item 
                and assign it as a unique key to the list item */}
              </View>
            )
          }}
          keyExtractor={(item,index)=>{
            return item.id;
          }}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  appContainer:{
    flex:1,
    paddingTop:25,
    paddingHorizontal:16
  },
  inputContainer:{
    flex:1,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    marginBottom:20,
    borderBottomWidth:1,
    borderBottomColor:'#cccccc',
  },
  textInput:{
    borderWidth:1,
    borderColor:'#cccccc',
    width:'70%',
    marginRight:8,
    padding:8,
  },
  goalContainer:{
    flex:4,
  },
  goalItem:{
    borderRadius:10,
    backgroundColor:'blue',
    margin:8,
    padding:8,
  },
});
